name: Load Testing QuickPizza with Report
on:
   - workflow_dispatch
   
jobs:
    loadtest:
        runs-on: ubuntu-latest
        
        services:
            quickpizza:
                image: ghcr.io/grafana/quickpizza-local:0.11.4
                ports:
                    - 3333:3333
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run local k6 test
          uses: grafana/k6-action@v0.3.1
          with:
            filename: ./foundations/01.basic.js
          env:
            BASE_URL: "http://quickpizza:3333"  

        - name: Upload Report
          uses: actions/upload-artifact@v2
          with:
            name: report
            path: summary.html    